"""Initial migration

Revision ID: a0acec51db93
Revises: 
Create Date: 2024-12-19 16:10:43.134444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0acec51db93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('min_amount', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_rates_max_amount'), ['max_amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_rates_min_amount'), ['min_amount'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wa_id', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_wa_id'), ['wa_id'], unique=True)

    op.create_table('chat_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_logs_user_id'), ['user_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('property_reference', sa.String(length=50), nullable=True),
    sa.Column('original_loan_amount', sa.Float(), nullable=False),
    sa.Column('original_loan_tenure', sa.Integer(), nullable=False),
    sa.Column('current_repayment', sa.Float(), nullable=False),
    sa.Column('new_repayment', sa.Float(), nullable=True),
    sa.Column('monthly_savings', sa.Float(), nullable=True),
    sa.Column('yearly_savings', sa.Float(), nullable=True),
    sa.Column('total_savings', sa.Float(), nullable=True),
    sa.Column('years_saved', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('remaining_tenure', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_reference')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_user_id'))

    op.drop_table('leads')
    with op.batch_alter_table('chat_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_logs_user_id'))

    op.drop_table('chat_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_wa_id'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))

    op.drop_table('users')
    with op.batch_alter_table('bank_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_rates_min_amount'))
        batch_op.drop_index(batch_op.f('ix_bank_rates_max_amount'))

    op.drop_table('bank_rates')
    # ### end Alembic commands ###
